services:
  - type: web
    name: wordpress
    env: docker
    plan: starter
    dockerComposePath: ./docker-compose.yml
    envVars:
      - key: WORDPRESS_DB_HOST
        value: db:3306
      - key: WORDPRESS_DB_USER
        value: wpuser
      - key: WORDPRESS_DB_PASSWORD
        value: wppassword
      - key: WORDPRESS_DB_NAME
        value: wpdb
